name: Run tests

on:
  push:
    paths:
      - Api/**
      - ApiTest/**
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - Api/**
      - ApiTest/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from api-test

